# Generated by Django 5.1.2 on 2024-10-14 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('name_father_Author', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=150)),
                ('place', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('page_start', models.IntegerField()),
                ('page_end', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=30)),
                ('name_father_Author', models.CharField(max_length=4)),
                ('title', models.CharField(max_length=200)),
                ('publisher', models.CharField(max_length=50)),
                ('number_tom', models.IntegerField()),
                ('year', models.IntegerField()),
                ('page_start', models.IntegerField()),
                ('page_end', models.IntegerField()),
            ],
        ),
    ]
