# Generated by Django 5.1.2 on 2024-10-14 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_conf_journal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=30)),
                ('UserPasword', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='name_father_Author',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='conf',
            name='name_father_Author',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='journal',
            name='name_father_Author',
            field=models.CharField(max_length=5),
        ),
    ]
